### ISSUE TITLE
allow SSH tunnelling to host OS 

### ISSUE THREAD

**Issue by sponnet** [AvadoDServer/AVADO-DNP-RemoteConnect#13]
As a user I want to be able to connect to the host OS through ssh to troubleshoot. This feature should be activated in the remoteconnect package before it works for security reasons.

command to forward port

``` iptables -t nat -A PREROUTING -p tcp --dport 22 -j DNAT --to-destination HOSTIP:22```

Questions:

- how to determine host address
- how to remove rule later on

**Comment by sponnet** [comment]
see also https://github.com/AvadoDServer/DNP_DAPPMANAGER/blob/master/build/src/src/utils/getInternalIp.js
how to determine host IP

**Comment by heeckhau** [comment]
Get host IP from docker container:
https://stackoverflow.com/questions/22944631/how-to-get-the-ip-address-of-the-docker-host-from-inside-a-docker-container
